[package]
name = "lp-riscv-emu-guest"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
linked_list_allocator = { version = "0.10", default-features = false, features = ["use_spin"] }
lp-riscv-emu-shared = { path = "../lp-riscv-emu-shared" }
log = { workspace = true, default-features = false }

[build-dependencies]
