[package]
name = "lp-emu-guest-test-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "lp-emu-guest-test-app"
path = "src/main.rs"
test = false

[profile.release]
panic = "abort"

[build-dependencies]

[dependencies]
lp-emu-guest = { path = "../lp-emu-guest" }
