[package]
name = "lp-riscv-emu"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0 WITH LLVM-exception"
description = "RISC-V 32-bit emulator runtime"

[lints]
workspace = true

[dependencies]
lp-riscv-inst = { path = "../lp-riscv-inst" }
lp-riscv-emu-shared = { path = "../lp-riscv-emu-shared" }
cranelift-codegen = { workspace = true, features = ["riscv32"] }
hashbrown = { workspace = true }
log = { workspace = true, default-features = false }
env_logger = { workspace = true, optional = true }

[features]
std = ["env_logger", "log/std"]  # For time tracking (std::time::Instant) and debug output (std::io::Write)

[dev-dependencies]
cranelift-codegen = { workspace = true, features = ["riscv32"] }
cranelift-frontend = { workspace = true }
cranelift-module = { workspace = true }
lp-riscv-elf = { path = "../lp-riscv-elf", features = ["std"] }
