[package]
name = "fw-esp32"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["esp32c6"]
esp32c6 = [
    "esp-backtrace/esp32c6",
    "esp-bootloader-esp-idf/esp32c6",
    "esp-rtos/esp32c6",
    "esp-hal/esp32c6",
]

[dependencies]
embassy-executor = "0.9.1"
embassy-time = "0.4.0"
esp-backtrace = { version = "0.18.1", features = ["panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.2.0" }
esp-hal = { version = "1.0.0", features = ["log-04", "unstable"] }
esp-rtos = { version = "0.2.0", features = ["embassy", "log-04"] }
esp-println = { version = "0.16.1", features = ["log-04"] }
esp-alloc = { version = "0.8.0", features = ["internal-heap-stats"] }

fw-core = { path = "../../crates/fw-core", default-features = false }
lp-server = { path = "../../crates/lp-server", default-features = false }
lp-shared = { path = "../../crates/lp-shared", default-features = false }
lp-model = { path = "../../crates/lp-model", default-features = false }
hashbrown = { workspace = true }

[lints]
workspace = true
