[package]
name = "lp-builtins"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["lib"]

[features]
default = []
std = []
test = ["std"]
test_hash_fixed = []
test_visual = ["std"]

[dependencies]
lpfx-impl-macro = { path = "../lpfx-impl-macro" }

[dev-dependencies]
noise = "0.9"

