[package]
name = "fw-emu"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fw-core = { path = "../fw-core", default-features = false }
lp-server = { path = "../../lp-core/lp-server", default-features = false }
lp-shared = { path = "../../lp-core/lp-shared", default-features = false }
lp-model = { path = "../../lp-core/lp-model", default-features = false }
lp-riscv-tools = { path = "../../lp-rv32/lp-riscv-tools", default-features = false }
lp-emu-guest = { path = "../../lp-rv32/lp-emu-guest" }
lp-builtins = { path = "../../lp-glsl/crates/lp-builtins", default-features = false }
hashbrown = { workspace = true }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }

[build-dependencies]

[lints]
workspace = true
